---
# roles file for jira

- src: https://github.com/pantarei/ansible-role-apt
  name: apt

- src: https://github.com/pantarei/ansible-role-java
  name: java

- src: https://github.com/pantarei/ansible-role-jira
  name: jira
